name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"] # Se ejecuta cada vez que subes cambios a master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './index.html' # Indica la carpeta donde está tu index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4